config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  get '/about' => 'pages#about'
  get '/tour' => 'pages#tour'
  get '/music' => 'pages#music'

  resources :signups, only: [:new, :create]

end

app/models/signup.rb
class Signup < ActiveRecord::Base
	validates_presence_of :email
	validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i

	def subscribe
		mailchimp = Gibbon::API.new
		result = mailchimp.lists.subscribe({
		:id => ENV['MAILCHIMP_LIST_ID'],
		:email => {:email => self.email},
		:double_optin => false,
		:update_existing => true,
		:send_welcome => true
		})
		Rails.logger.info("Subscribed #{self.email} to MailChimp") if result
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end

	def about
	end

	def tour
	end

	def music
	end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController

	def new
		@signup = Signup.new
	end

	def create
		@signup = Signup.new(secure_params)
		if @signup.valid?
			@signup.subscribe
			redirect_to root_path
		else
			render :new
		end
	end

	private

	def secure_params
		params.require(:signup).permit(:email)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BAU</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
		
	<div id="wrap">
		<nav class="navbar navbar-inverse" role="navigation">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <%= link_to 'Business As Usual', root_path, :class => 'navbar-brand' %>
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">
		      </ul>
		      <ul class="nav navbar-nav navbar-right">
		        <li><%= link_to 'About', about_path %></li>
		        <li><%= link_to 'Music', music_path %></li>
		        <li><%= link_to 'Tour', tour_path %></li>
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>

<%= yield %>

	</div>

	<div class="clr" />

	<div id="footer">
		<div class="container text-center">
				<%= link_to 'https://www.facebook.com/BAUsual/' do %>
					<i class="icon-facebook"></i>
				<% end %>
				<%= link_to 'https://twitter.com/BAU_Chicago' do %>
					<i class="icon-twitter"></i>
				<% end %>
				<%= link_to 'https://www.youtube.com/channel/UChRG42LPttfLZgR0DVVUaiw' do %>
					<i class="icon-youtube"></i>
				<% end %>
				<%= link_to 'https://soundcloud.com/businessasusual-1/' do %>
					<i class="icon-soundcloud"></i>
				<% end %>
		</div>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<div class="col-xs-10 col-xs-offset-1 text-center">
	<br />
	<h1>About</h1>
	<div class="boxx text-left">
		<p>Business As Usual is a four piece dance-rock band based out of Chicago, IL. Forming in 2013, BAU's has spent the next two years playing high energy, multi-set shows all over Chicago and a few other Midwest locations. Each BAU show is a one-of-a-kind experience, taking the listener on a musical journey. Seamlessly blending elements of rock, electronica, funk, dub, and even bits of ska, the genre-hopping quartet is able to launch off into sections of exciting and memorable improvisation as they guide through different odds and ends of their catchy compositions. You've just been warned, your next Business meeting is mandatory.</p>
	</div>
	<div class="boxx text-left">
		<p>The band consists of Chief E-Drum Officer Gary Goodheart (drums), Chairman of the Boards Sean McKeon (keys), Senior Infrastructure Developer Daniel Ranieri (bass), and Lead Tatics Specialist Adrian Slezak (guitar). Want to get in touch with one us? Email the band <%= mail_to 'gears@bauband.com', 'here' %>.
		<br />
		<br />
		<p>If you are interested in booking Business As Usual, please contact our manager Nick by clicking <%= mail_to 'nick@bauband.com', 'here' %>.
		<br />
		<br />
		<p>All photos on the site are courtesy of Abby Matthews unless noted. You can check out more of her awesome work <%= link_to 'here', 'http://www.abbyfoxphotography.com/' %>.
	</div>
</div>

app/views/pages/home.html.erb
<h1>This is the home page</h1>

app/views/pages/index.html.erb
<div class="hero">
	<br />
	<div class="frosty col-xs-10 col-xs-offset-1 text-center">
		<br />
		<h4>Enter Your Email To Get Our Boardroom Meeting Minutes</h4>
		<br />
		<br />
			<%= simple_form_for :signup, :url => signups_path do |f| %>
			  <%= f.input :email, label: false, :placeholder => 'Your Email Here...' %>
			  <br />
			  <%= f.submit 'Sign Up!', :class => 'btn btn-danger' %>
			<% end %>
			<br>
		</div>
		<div class="clr"></div>
		<br />

		<div class="col-xs-6 col-xs-offset-1 text-center">
   	<div class="frosty" style="padding-left: 10px">
   	<br />
   	<div class="fb-post" data-href="https://www.facebook.com/BAUsual/photos/a.384342688342324.1073741827.362970287146231/653586491417941/?type=1" data-width="350"></div>
   	<br />
   	</div>
   	</div>

		<div class="col-xs-3 text-center">

       <div style="width: 100%; text-align: center; overflow: hidden; width: 240px; margin:0 auto;">
       	<div class="frosty">
	       <a class="twitter-timeline" data-dnt="true" href="https://twitter.com/bau_chicago" data-widget-id="564641978797682689" data-chrome="nofooter noborders noheader noborders noscrollbar transparent" height="329" data-link-color="#FF2B4F" data-theme="dark">Tweets by @BAU_Chicago</a>
	       <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script> 
	     	</div>
   		</div>



    </div>


</div>

app/views/pages/music.html.erb
<div class="col-xs-10 col-xs-offset-1 text-center">
	<br />
	<h1>Music</h1>
	<div class="boxx text-center">
		<h3>Listen to us on <%= link_to 'Archive', 'https://archive.org/details/BusinessAsUsual'%>, <%= link_to 'Soundcloud', 'https://soundcloud.com/businessasusual-1/' %>, and <%= link_to 'YouTube', 'https://www.youtube.com/channel/UChRG42LPttfLZgR0DVVUaiw' %>!</h3>
		<br />
		<br />
		<h4>Business As Usual Live at Windy City Inn on 2014-12-31</h4>
		<br />
		<iframe src="https://archive.org/embed/bau2014-12-31.flac16" width="640" height="30" frameborder="0" webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen></iframe>
		<br />
		<br />
		<h4>Ending of Gears from NYE 2014</h4>
		<br />
		<iframe width="640" height="300" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/185096287&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
		<br />
		<br />
		<h4>2014 Improv Highlights</h4>
	  </br>
		<iframe width="640" height="360" src="//www.youtube.com/embed/R59RYDyz8kU?feature=player_embedded" frameborder="0" allowfullscreen></iframe>
	</div>

</div>

app/views/pages/tour.html.erb
<div class="col-xs-10 col-xs-offset-1 text-center">
	<br />
	<h1>Upcoming Shows</h1>
	<br />
		<div class="boxx col-xs-10 col-xs-offset-1 text-center">
			<h3>February 28th, 2015 at House of Blues</h3>
			<br />
			<h4>329 North Dearborn Street<br />Chicago, IL 60654</h4>
			<br />
			<h5>With Spread, Chicago Funk Mafia, Walsher Clemons, and Jaik Willis</h5>
			<br>
			<%= link_to 'Tickets', 'https://www.facebook.com/BAUsual/photos/a.384342688342324.1073741827.362970287146231/653586491417941/?type=1' %>
		</div>
		<div class="boxx col-xs-10 col-xs-offset-1 text-center">
			<h3>March 12th, 2015 at The Tonic Room</h3>
			<br />
			<h4>2477 North Halsted Street<br />Chicago, IL 60614</h4>
			<br />
			<h5>With Mister F</h5>
			<br>
			<%= link_to 'Tickets', 'https://www.ticketfly.com/purchase/event/770403' %>
		</div>
</div>